apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - api-hpa.yaml
