apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: "prod_super_secret_jwt_key_replace_me"
  POSTGRES_PASSWORD: "postgres@2025"
